# Generated by Django 2.1.2 on 2018-10-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
